/**
 * Automated System Setup for ClawTeam
 * 
 * This script clones the ClawTeam repository, installs dependencies,
 * and sets up a local binary shim in ~/.local/bin/clawteam-gateway.
 */

const { spawnSync } = require('child_process');
const fs = require('fs');
const path = require('path');
const os = require('os');

const REPO_URL = 'https://github.com/dcstrange/ClawTeam.git';
const INSTALL_DIR = path.join(os.homedir(), 'ClawTeam');
const BIN_DIR = path.join(os.homedir(), '.local', 'bin');
const SHIM_PATH = path.join(BIN_DIR, 'clawteam-gateway');

function log(msg) { console.log(`[setup] ${msg}`); }
function error(msg) { console.error(`[error] ${msg}`); process.exit(1); }

function run(cmd, args, options = {}) {
  const result = spawnSync(cmd, args, { stdio: 'inherit', shell: true, ...options });
  if (result.status !== 0) {
    error(`Command failed: ${cmd} ${args.join(' ')}`);
  }
}

async function setup() {
  log('Starting ClawTeam automated setup...');

  // 1. Check prerequisites
  log('Checking prerequisites...');
  const prereqs = ['git', 'npm', 'node'];
  for (const p of prereqs) {
    if (spawnSync(p, ['--version']).status !== 0) {
      error(`Prerequisite not found: ${p}. Please install it first.`);
    }
  }

  // 2. Clone repository
  if (fs.existsSync(INSTALL_DIR)) {
    log(`ClawTeam directory already exists at ${INSTALL_DIR}. Updating...`);
    run('git', ['pull'], { cwd: INSTALL_DIR });
  } else {
    log(`Cloning ClawTeam repository to ${INSTALL_DIR}...`);
    run('git', ['clone', REPO_URL, INSTALL_DIR]);
  }

  // 3. Install dependencies
  log('Installing dependencies (this may take a minute)...');
  run('npm', ['install'], { cwd: INSTALL_DIR });

  // 4. Create binary shim
  log(`Creating binary shim at ${SHIM_PATH}...`);
  if (!fs.existsSync(BIN_DIR)) {
    fs.mkdirSync(BIN_DIR, { recursive: true });
  }

  const nodePath = process.execPath;
  const scriptPath = path.join(INSTALL_DIR, 'packages', 'clawteam-gateway', 'src', 'index.ts');
  
  const shimContent = `#!/bin/bash
# ClawTeam Gateway Shim generated by supercli
export PATH="${path.dirname(nodePath)}:$PATH"
export CLAWTEAM_API_KEY=\${CLAWTEAM_API_KEY:-test-key}
export GATEWAY_ENABLED=true
export GATEWAY_PORT=\${GATEWAY_PORT:-3100}

cd "${INSTALL_DIR}"
exec npx tsx "${scriptPath}" "$@"
`;

  fs.writeFileSync(SHIM_PATH, shimContent, { mode: 0o755 });

  log('Setup complete!');
  log(`You can now run 'clawteam-gateway' if ${BIN_DIR} is in your PATH.`);
  log('Try: supercli clawteam system status');
}

setup().catch(err => {
  error(`Setup failed: ${err.message}`);
});
